# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

import os
os.environ['QT_QPA_PLATFORM_PLUGIN_PATH'] = 'platforms'

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 650)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        MainWindow.setFont(font)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_main_title = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        self.label_main_title.setFont(font)
        self.label_main_title.setAlignment(QtCore.Qt.AlignCenter)
        self.label_main_title.setObjectName("label_main_title")
        self.verticalLayout.addWidget(self.label_main_title)
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName("tabWidget")
        
        # ==================== Tab Caesar ====================
        self.tab_caesar = self.create_cipher_tab("caesar", "Caesar")
        self.tabWidget.addTab(self.tab_caesar, "Caesar")

        # ==================== Tab Vigenere ====================
        self.tab_vigenere = self.create_cipher_tab("vigenere", "Vigenère")
        self.tabWidget.addTab(self.tab_vigenere, "Vigenère")

        # ==================== Tab Rail Fence ====================
        self.tab_railfence = self.create_cipher_tab("railfence", "Rail Fence")
        self.tabWidget.addTab(self.tab_railfence, "Rail Fence")

        # ==================== Tab Playfair ====================
        self.tab_playfair = self.create_cipher_tab("playfair", "Playfair")
        self.tabWidget.addTab(self.tab_playfair, "Playfair")

        # ==================== Tab Transposition ====================
        self.tab_transposition = self.create_cipher_tab("transposition", "Transposition")
        self.tabWidget.addTab(self.tab_transposition, "Transposition")

        self.verticalLayout.addWidget(self.tabWidget)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def create_cipher_tab(self, name, title):
        """Hàm trợ giúp để tạo một tab cho mỗi thuật toán mã hóa."""
        tab = QtWidgets.QWidget()
        tab.setObjectName(f"tab_{name}")
        
        gridLayout = QtWidgets.QGridLayout(tab)
        gridLayout.setObjectName(f"gridLayout_{name}")
        
        # Plain text
        label_plain = QtWidgets.QLabel(tab)
        label_plain.setObjectName(f"{name}_label_plain")
        gridLayout.addWidget(label_plain, 0, 0, 1, 1)
        
        text_edit_plain = QtWidgets.QTextEdit(tab)
        text_edit_plain.setObjectName(f"{name}_text_plain")
        gridLayout.addWidget(text_edit_plain, 1, 0, 1, 2)
        
        # Key
        label_key = QtWidgets.QLabel(tab)
        label_key.setObjectName(f"{name}_label_key")
        gridLayout.addWidget(label_key, 2, 0, 1, 1)
        
        line_edit_key = QtWidgets.QLineEdit(tab)
        line_edit_key.setObjectName(f"{name}_line_key")
        gridLayout.addWidget(line_edit_key, 2, 1, 1, 1)
        
        # Cipher text
        label_cipher = QtWidgets.QLabel(tab)
        label_cipher.setObjectName(f"{name}_label_cipher")
        gridLayout.addWidget(label_cipher, 3, 0, 1, 1)
        
        text_edit_cipher = QtWidgets.QTextEdit(tab)
        text_edit_cipher.setObjectName(f"{name}_text_cipher")
        gridLayout.addWidget(text_edit_cipher, 4, 0, 1, 2)
        
        # Buttons
        button_encrypt = QtWidgets.QPushButton(tab)
        button_encrypt.setObjectName(f"{name}_btn_encrypt")
        gridLayout.addWidget(button_encrypt, 5, 0, 1, 1)
        
        button_decrypt = QtWidgets.QPushButton(tab)
        button_decrypt.setObjectName(f"{name}_btn_decrypt")
        gridLayout.addWidget(button_decrypt, 5, 1, 1, 1)
        
        # Gán các widget vào thuộc tính của class để truy cập từ bên ngoài
        setattr(self, f"{name}_text_plain", text_edit_plain)
        setattr(self, f"{name}_line_key", line_edit_key)
        setattr(self, f"{name}_text_cipher", text_edit_cipher)
        setattr(self, f"{name}_btn_encrypt", button_encrypt)
        setattr(self, f"{name}_btn_decrypt", button_decrypt)

        # Đặt tên cho các label
        label_plain.setText("Văn bản gốc (Plaintext):")
        label_key.setText("Khóa (Key):")
        label_cipher.setText("Văn bản mã hóa (Ciphertext):")
        button_encrypt.setText(f"Mã hóa {title}")
        button_decrypt.setText(f"Giải mã {title}")
        
        return tab

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Công Cụ Mã Hóa Cổ Điển"))
        self.label_main_title.setText(_translate("MainWindow", "BẢO MẬT THÔNG TIN NÂNG CAO"))

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
