# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'websocket_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

import os
os.environ['QT_QPA_PLATFORM_PLUGIN_PATH'] = '.\\platforms'


from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(750, 550)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        MainWindow.setFont(font)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_title = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        self.label_title.setFont(font)
        self.label_title.setAlignment(QtCore.Qt.AlignCenter)
        self.label_title.setObjectName("label_title")
        self.verticalLayout.addWidget(self.label_title)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        self.txtUrl = QtWidgets.QLineEdit(self.centralwidget)
        self.txtUrl.setObjectName("txtUrl")
        self.horizontalLayout_2.addWidget(self.txtUrl)
        self.btnConnect = QtWidgets.QPushButton(self.centralwidget)
        self.btnConnect.setObjectName("btnConnect")
        self.horizontalLayout_2.addWidget(self.btnConnect)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.txtMessage = QtWidgets.QLineEdit(self.centralwidget)
        self.txtMessage.setEnabled(False)
        self.txtMessage.setObjectName("txtMessage")
        self.horizontalLayout.addWidget(self.txtMessage)
        self.btnSend = QtWidgets.QPushButton(self.centralwidget)
        self.btnSend.setEnabled(False)
        self.btnSend.setObjectName("btnSend")
        self.horizontalLayout.addWidget(self.btnSend)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setBold(True)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.verticalLayout.addWidget(self.label_3)
        self.txtLog = QtWidgets.QTextEdit(self.centralwidget)
        self.txtLog.setReadOnly(True)
        self.txtLog.setObjectName("txtLog")
        self.verticalLayout.addWidget(self.txtLog)
        self.gridLayout.addLayout(self.verticalLayout, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "WebSocket AES Client"))
        self.label_title.setText(_translate("MainWindow", "WEBSOCKET AES CLIENT"))
        self.label.setText(_translate("MainWindow", "Server URL:"))
        self.txtUrl.setText(_translate("MainWindow", "ws://localhost:8889/websocket"))
        self.btnConnect.setText(_translate("MainWindow", "Kết nối"))
        self.label_2.setText(_translate("MainWindow", "Tin nhắn gửi đi:"))
        self.txtMessage.setPlaceholderText(_translate("MainWindow", "Nhập tin nhắn..."))
        self.btnSend.setText(_translate("MainWindow", "Gửi và Mã hóa"))
        self.label_3.setText(_translate("MainWindow", "Log:"))